#ifndef _____ENGLISH__
#define _____ENGLISH__

#define INFO "Information"
#define WARNING "Warning!"
#define ERROR "Error"
#define QUESTION "Question"
#define MSG_BTNOK "&OK"
#define MSG_BTNCANCEL "Ca&ncel"
#define MSG_BTNPLAY "&Play"
#define MSG_BTNOPEN "&Open..."
#define MSG_BTNOPENDIR "Open d&irectory..."
#define MSG_BTNMOVEUP "Move &up"
#define MSG_BTNDELETE "&Delete"
#define MSG_BTNDELETEALL "Delete &all"
#define MSG_PLTRIM L"&Trim"
#define MSG_PLSORT "&Sort"
#define MSG_PLSORTFILE "By &filename"
#define MSG_PLSORTTITLE "By &title"
#define MSG_PLSORTARTIST "By &artist"
#define MSG_PLSORTALBUM "By a&lbum"
#define MSG_BTNMOVEDOWN "Move do&wn"
#define MSG_BTNPROP "&Properties..."
#define MSG_BTNADD "&Add..."
#define MSG_BTNCLOSE "Close"
#define MSG_BTNPLSAVE "Sa&ve as..."
#define MSG_BTNINDEX "Inde&x all"
#define MSG_QUICKFILTER "&Quick filter: "
#define MSG_DLGOPENDIR "Open directory..."
#define MSG_NOPLAYING "No file currently playing"
#define MSG_NOWRITEPLAYLIST L"No playlist save format supported."
#define MSG_ENCODECOPYORIG "Copy in original format"
#define MSG_ENCODECOPYORIGFAIL L"The copy failed!"
#define MSG_ENCODEFAIL L"The encoding failed to start."
#define MSG_ENCODEOPTIONS "For&mat options..."
#define MSG_ALLFILES "All files (*.*)"
#define MSG_ALLSUPFILES L"All supported files"
#define MSG_LOOP_ON L"Loop on"
#define MSG_LOOP_OFF L"Loop off"
#define MSG_RANDOM_ON L"Random on"
#define MSG_RANDOM_OFF L"Random off"
#define MSG_REVERSE_ON L"Reverse playing order"
#define MSG_REVERSE_OFF L"Normal playing order"
#define MSG_INTRO_MODE_ON L"Intro mode on"
#define MSG_INTRO_MODE_OFF L"Intro mode off"
#define MSG_CROSSFADE_ON L"Crossfade on"
#define MSG_CROSSFADE_OFF L"Crossfade off"
#define MSG_OPENURL_TITLE  "Open URL"
#define MSG_OPENURL_PROMPT "Type or paste the URL to open: "
#define MSG_GOTOTIME_TITLE "Time jump"
#define MSG_GOTOTIME_PROMPT "Indicate the time position to jump to: "
#define MSG_PLAYLISTDLG "Playlist"
#define MSG_LBLPLAYLIST "&Playlist : "
#define MSG_INDEXDLG "Indexing"
#define MSG_INDEXPROGRESS "%d elements indexed out of %d"
#define MSG_RADIODLG "Radios"
#define MSG_LBLRADIO "&Radio : "
#define MSG_LBLGENRE "&Genre: "
#define MSG_LBLLANG "La&nguage: "
#define MSG_LBLCOUNTRY "&Country: "
#define MSG_ALLLANGS "-- All languages --"
#define MSG_ALLGENRES "-- All genres --"
#define MSG_ALLCOUNTRIES "-- All countries --"
#define MSG_CONFIRM "Confirmation"
#define MSG_CFMDELRADIO L"Are you sure to delete \"%s\" ?\r\nThis operation isn't reversable."
#define MSG_RADIOPROPS "Properties"
#define MSG_RADIO_NAME "&Name: "
#define MSG_RADIO_GENRE "&Genre: "
#define MSG_RADIO_LANG "&Language: "
#define MSG_RADIO_COUNTRY "&Country: "
#define MSG_RADIO_DESC "&Description: "
#define MSG_RADIO_URLS "&URL: "
#define MSG_FILEINFORMATION "File informations"
#define MSG_FI_FILENAME "File name:\t"
#define MSG_FI_FILEPATH "File path:\t"
#define MSG_FI_FILESIZE "File size:\t"
#define MSG_SIZE_B " bytes"
#define MSG_SIZE_KB " KB"
#define MSG_SIZE_MB " MB"
#define MSG_SIZE_GB " GB"
#define MSG_SIZE_TB " TB"
#define MSG_FI_BITRATE L"Average bitrate:\t%d kbps"
#define MSG_FI_URL "URL:\t"
#define MSG_FI_TITLE "Title:\t"
#define MSG_FI_ARTIST "Artist:\t"
#define MSG_FI_ALBUM "Album:\t"
#define MSG_FI_GENRE "Genre:\t"
#define MSG_FI_SUBTITLE "subtitle:\t"
#define MSG_FI_DURATION L"Duration:\t"
#define MSG_FI_COPYRIGHT "Copyright:\t"
#define MSG_FI_COMPOSER "Composer:\t"
#define MSG_FI_COMMENT "Comment:\t"
#define MSG_FI_YEAR L"Year:\t"
#define MSG_FI_DISC L"Disc number:\t"
#define MSG_FI_TRACKNUM L"Track number:\t"
#define MSG_FI_FREQ L"Sample rate:\t"
#define MSG_FI_CTYPE "Type: "
#define MSG_FI_NCHAN "Number of channels"
#define MSG_FI_BITRES L"Resolution:\t%d bits"
#define MSG_FI_MODINFO "Instruments:"
#define MSG_FI_MODINST "#%d:\t%hs"
#define MSG_FI_NONE "none"
#define MSG_FI_COPYINFO "&Copy to clipboard"
#define MSG_FI_MODIFYBTN "&Modify..."
#define MSG_FI_UPDATEBTN "&Save"
#define MSG_FI_TAGSAVEFAILED L"Tags in the file couldn't be updated."
#define MSG_FI_MODIFYDLG "Modification"
#define MSG_FI_MODIFYDLG2 "Enter the new value : "
#define MSG_OPTIONSDLG "Options"
#define MSG_OPTIONS_DEVICES L"Devices"
#define MSG_OPTD_OUTPUT "Playing:"
#define MSG_OPTD_INPUT "Recording:"
#define MSG_OPTD_FEEDBACK "Mic feedback:"
#define MSG_OPTD_PREVIEW L"Preview:"
#define MSG_OPTD_JINGLE "Jingles:"
#define MSG_DEFAULTDEVICE "Default device"
#define MSG_OPT_INTEGRATION L"Integration"
#define MSG_OPT_REUSE_INSTANCES L"Allow concurrent running instances"
#define MSG_OPT_FOCUSONOPEN L"Focus player window when opening a file from explorer"
#define MSG_OPT_ACTIONONOPEN L"When opening a file from windows explorer:"
#define MSG_OPT_CLEARONOPEN "Start playing and create a new playlist"
#define MSG_OPT_APPENDONOPEN L"Add to playlist"
#define MSG_OPT_LISTENAPPENDONOPEN "Add to playlist and start playing"
#define MSG_OPT_OPENPREVIEW L"Enable preview in open dialog"
#define MSG_OPT_CASTING "Broadcasting"
#define MSG_OPTC_NOFEEDBACK "Disable mic feedback when broadcast is active"
#define MSG_OPTC_AUTOTITLE "Send song title to the stream"
#define MSG_OPTC_USEJINGLES "Enable jingle mode (with spacebar on the playlist)"
#define MSG_OPT_ADVANCED L"Advanced"
#define MSG_OPTX_SCRIPTING "Enable lua scripting"
#define MSG_OPTX_WEBSERV "Enable control web server"
#define MSG_OPTX_SERVPORT "Listening port:"
#define MSG_OPT_GENERAL L"General"
#define MSG_OPTG_CHECKUPDATES "Check for updates at each start"
#define MSG_OPTG_RELOADLAST "At start, continue playing where last stopped"
#define MSG_CAST_TITLE "Web broadcasting"
#define MSG_CAST_TYPE "Type: "
#define MSG_CAST_FORMAT "Format: "
#define MSG_CAST_HOST "Server: "
#define MSG_CAST_PORT "Port: "
#define MSG_CAST_NAME "Server name: "
#define MSG_CAST_PASSWORD "Password: "
#define MSG_CAST_URL "URL: "
#define MSG_CAST_GENRE "Genre: "
#define MSG_CAST_DESC "Description: "
#define MSG_SHOUTCAST "Shoutcast"
#define MSG_ICECAST "Icecast"
#define MSG_CASTDIRECT "Direct server"
#define MSG_CASTFAIL L"The web broadcasting failed to start."
#define MSG_MIDIDLG "MIDI Panel"
#define MSG_MIDI_LBLLYRIC "Lyrics: "
#define MSG_MIDI_CHANNEL "Channel "

#define MSG_ABOUTTITLE L"About 6player"
#define MSG_ABOUTTEXT "6Player, version 4.0 alpha\r\nCopyright © 2011-2014, QuentinC\r\nMore info at http://quentinc.net/ "

#define MSG_FILEMENU "&File"
#define MSG_FILEOPEN "&Open...\aCtrl+O"
#define MSG_FILEOPENURL "Open &URL...\aCtrl+U"
#define MSG_FILEOPENAPPEND "Open and add to pla&ylist...\aCtrl+Maj+O"
#define MSG_FILEOPENURLAPPEND "Open URL and add to pla&ylist...\aCtrl+Maj+U"
#define MSG_FILEOPENDIR "Open &directory...\aCtrl+D"
#define MSG_FILEOPENDIRAPPEND "Open directory and add to pla&ylist...\aCtrl+Maj+D"
#define MSG_FILEOPENRADIO "Radios...\aAlt+R"
#define MSG_FILESAVE "Sa&ve as...\aCtrl+S"
#define MSG_FILEINFO4 "Properties\aF3"
#define MSG_FILESAVEALL "E&xport entire playlist"
#define MSG_FILESAVEALL2 "Export entire playlist"
#define MSG_FILEOPTIONS "Opt&ions...\aCtrl+P"
#define MSG_FILEQUIT "E&xit\aAlt+F4"
#define MSG_LECTMENU "Pla&yer"
#define MSG_LECTPAUSE "&Play/pause\aC"
#define MSG_LECTNEXT "&Next song\aL"
#define MSG_LECTPREV "Pre&vious song\aK"
#define MSG_LECTGOTOTIME "Time &jump...\aCtrl+J"
#define MSG_LECTSAVE "&Save playlist...\aCtrl+Maj+S"
#define MSG_LECTDEV "&Audio devices...\aF6"
#define MSG_LECTLOOP "&Loop\aI"
#define MSG_LECTRAND "&Random\aP"
#define MSG_LECTREVERSE "Reverse &order\aMaj+P"
#define MSG_LECTINTRO "&Intro mode\aMaj+I"
#define MSG_LECTFADE "Cross&fade\aN"
#define MSG_PLISTMENU "Play&list"
#define MSG_PLMDELSONG "&Delete current song\aSuppr"
#define MSG_PLMSHOWPLAYLIST "S&how playlist\aAlt+P"
#define MSG_INDEXPLAYLIST "Inde&x playlist\aCtrl+Maj+X"
#define MSG_RECORD_TOGGLE "Turn &mic on/off\aF4"
#define MSG_MIDIDLG_TOGGLE "Show M&IDI panel\aAlt+M"
#define MSG_CASTING "&Web broadcast...\aCtrl+Maj+W"
#define MSG_EFFECTSMENU "Effe&cts"
#define MSG_EFF_MODE "Apply to"
#define MSG_EFF_MODE1 "Playing stream"
#define MSG_EFF_MODE2 "Microphone"
#define MSG_EFF_MODE3 "Broadcast"
#define MSG_HELPMENU "&?"
#define MSG_HELPABOUT "&About..."

#endif
