#ifndef _____FRENCH__
#define _____FRENCH__

#define INFO "Information"
#define WARNING "Attention !"
#define ERROR "Erreur"
#define QUESTION "Question"
#define MSG_BTNOK "&OK"
#define MSG_BTNCANCEL "A&nnuler"
#define MSG_BTNPLAY "&Lecture"
#define MSG_BTNOPEN "&Ouvrir..."
#define MSG_BTNOPENDIR "Ouvrir dossie&r..."
#define MSG_BTNMOVEUP "&Monter"
#define MSG_BTNDELETE "S&upprimer"
#define MSG_BTNDELETEALL "Supprimer &tout"
#define MSG_PLTRIM L"Tai&ller"
#define MSG_PLSORT "&Trier"
#define MSG_PLSORTFILE "Par nom de &fichier"
#define MSG_PLSORTTITLE "Par &titre"
#define MSG_PLSORTARTIST "Par &artiste"
#define MSG_PLSORTALBUM "Par a&lbum"
#define MSG_BTNMOVEDOWN "&Descendre"
#define MSG_BTNPROP "&Propriétés..."
#define MSG_BTNADD "&Ajouter..."
#define MSG_BTNCLOSE "Fermer"
#define MSG_BTNPLSAVE "&Enregistrer sous..."
#define MSG_BTNINDEX "Inde&xer tout"
#define MSG_QUICKFILTER "&Filtre rapide : "
#define MSG_DLGOPENDIR "Ouvrir un dossier"
#define MSG_NOPLAYING "Aucun fichier en cours de lecture"
#define MSG_NOWRITEPLAYLIST L"Aucun format d'enregistrement de playlist n'est support\xE9."
#define MSG_ENCODECOPYORIG "Copie au format d'origine"
#define MSG_ENCODECOPYORIGFAIL L"La copie a \xE9" L"chou\xE9"
#define MSG_ENCODEFAIL L"L'encodage  n'a pas pu d\xE9marrer."
#define MSG_ENCODEOPTIONS "&Options du format..."
#define MSG_ALLFILES "Tous les fichiers (*.*)"
#define MSG_ALLSUPFILES L"Tous les fichiers support\xE9s"
#define MSG_LOOP_ON L"Lecture en boucle activ\xE9" L"e"
#define MSG_LOOP_OFF L"Lecture en boucle d\xE9sactiv\xE9" L"e"
#define MSG_RANDOM_ON L"Lecture al\xE9" L"atoire activ\xE9" L"e"
#define MSG_RANDOM_OFF L"Lecture al\xE9" L"atoire d\xE9sactiv\xE9" L"e"
#define MSG_REVERSE_ON L"Lecture invers\xE9" L"e activ\xE9" L"e"
#define MSG_REVERSE_OFF L"Lecture invers\xE9" L"e d\xE9sactiv\xE9" L"e"
#define MSG_INTRO_MODE_ON L"Mode intro activ\xE9"
#define MSG_INTRO_MODE_OFF L"Mode intro d\xE9sactiv\xE9"
#define MSG_CROSSFADE_ON L"Fondu encha\xEEn\xE9 activ\xE9"
#define MSG_CROSSFADE_OFF L"Fondu encha\xEEn\xE9 d\xE9sactiv\xE9"
#define MSG_OPENURL_TITLE  "Ouvrir une URL"
#define MSG_OPENURL_PROMPT "Saisissez ou collez l'adresse URL à ouvrir : "
#define MSG_GOTOTIME_TITLE "Atteindre"
#define MSG_GOTOTIME_PROMPT "Indiquez la position à atteindre : "
#define MSG_PLAYLISTDLG "Playlist"
#define MSG_LBLPLAYLIST "&Playlist : "
#define MSG_INDEXDLG "Indexation"
#define MSG_INDEXPROGRESS "%d \xC3\xA9l\xC3\xA9ments index\xC3\xA9s sur %d"
#define MSG_RADIODLG "Radios"
#define MSG_LBLRADIO "&Radio : "
#define MSG_LBLGENRE "&Genre : "
#define MSG_LBLLANG "La&ngue : "
#define MSG_LBLCOUNTRY "Pa&ys : "
#define MSG_ALLLANGS "-- Toutes les langues --"
#define MSG_ALLGENRES "-- Tous les genres --"
#define MSG_ALLCOUNTRIES "-- Tous les pays --"
#define MSG_CONFIRM "Confirmation"
#define MSG_CFMDELRADIO L"\xCAtes-vous s\xFBr de vouloir supprimer \"%s\" ?\r\nCette op\xE9ration est irr\xE9versible."
#define MSG_RADIOPROPS "Propriétés"
#define MSG_RADIO_NAME "&Nom : "
#define MSG_RADIO_GENRE "&Genre : "
#define MSG_RADIO_LANG "&Langue : "
#define MSG_RADIO_COUNTRY "&Pays : "
#define MSG_RADIO_DESC "&Description : "
#define MSG_RADIO_URLS "&URL : "
#define MSG_FILEINFORMATION "Informations sur le fichier"
#define MSG_FI_FILENAME "Nom du fichier :\t"
#define MSG_FI_FILEPATH "Emplacement :\t"
#define MSG_FI_FILESIZE "Taille :\t"
#define MSG_SIZE_B " octets"
#define MSG_SIZE_KB " Ko"
#define MSG_SIZE_MB " Mo"
#define MSG_SIZE_GB " Go"
#define MSG_SIZE_TB " To"
#define MSG_FI_BITRATE L"D\xE9" L"bit moyen:\t%d kbps"
#define MSG_FI_URL "URL :\t"
#define MSG_FI_TITLE "Titre :\t"
#define MSG_FI_ARTIST "Artiste :\t"
#define MSG_FI_ALBUM "Album :\t"
#define MSG_FI_GENRE "Genre :\t"
#define MSG_FI_SUBTITLE "Sous-titre :\t"
#define MSG_FI_DURATION L"Dur\xE9" L"e :\t"
#define MSG_FI_COPYRIGHT "Copyright :\t"
#define MSG_FI_COMPOSER "Compositeur :\t"
#define MSG_FI_COMMENT "Commentaire :\t"
#define MSG_FI_YEAR L"Ann\xE9" L"e :\t"
#define MSG_FI_DISC L"N\xB0 de disque :\t"
#define MSG_FI_TRACKNUM L"N\xB0 de piste :\t"
#define MSG_FI_FREQ L"Fr\xE9quence d'\xE9" L"chantillonnage :\t"
#define MSG_FI_CTYPE "Type : "
#define MSG_FI_NCHAN "Nombre de canaux"
#define MSG_FI_BITRES L"R\xE9solution :\t%d bits"
#define MSG_FI_MODINFO "Instruments :"
#define MSG_FI_MODINST "#%d:\t%hs"
#define MSG_FI_NONE "aucun"
#define MSG_FI_COPYINFO "Copier dans le presse-papiers"
#define MSG_FI_MODIFYBTN "&Modifier..."
#define MSG_FI_UPDATEBTN "&Enregistrer"
#define MSG_FI_TAGSAVEFAILED L"L'enregistrement des tags dans le fichier a \xE9" L"chou\xE9"
#define MSG_FI_MODIFYDLG "Modification de la valeur"
#define MSG_FI_MODIFYDLG2 "Entrez la nouvelle valeur : "
#define MSG_OPTIONSDLG "Options"
#define MSG_OPTIONS_DEVICES L"P\xE9riph\xE9riques"
#define MSG_OPTD_OUTPUT "Lecture:"
#define MSG_OPTD_INPUT "Enregistrement:"
#define MSG_OPTD_AUXINPUT "Entrée auxiliaire:"
#define MSG_OPTD_FEEDBACK "Retour microphone:"
#define MSG_OPTD_AUXFEEDBACK "Retour entrée auxiliaire:"
#define MSG_OPTD_PREVIEW L"Aper\xE7us:"
#define MSG_OPTD_JINGLE "Jingles:"
#define MSG_DEFAULTDEVICE "Par d\xC3\xA9" "faut"
#define MSG_OPT_INTEGRATION L"Int\xE9gration"
#define MSG_OPT_REUSE_INSTANCES L"Autoriser l'ex\xE9" L"cution concurrente de plusieurs instances du logiciel"
#define MSG_OPT_FOCUSONOPEN L"Mettre la fen\xEAtre du lecteur au premier-plan lors de l'ouverture d'un fichier depuis l'explorateur windows"
#define MSG_OPT_ACTIONONOPEN L"Lors de l'ouverture d'un fichier depuis l'explorateur windows :"
#define MSG_OPT_CLEARONOPEN "Commencer la lecture et cr\xE9" L"er une nouvelle playlist"
#define MSG_OPT_APPENDONOPEN L"Ajouter \xE0 la playlist"
#define MSG_OPT_LISTENAPPENDONOPEN "Ajouter \xE0 la playlist et commencer la lecture"
#define MSG_OPT_OPENPREVIEW L"Activer l'aper\xE7u dans la bo\xEEte de dialogue Ouvrir"
#define MSG_OPT_CASTING "Diffusion"
#define MSG_OPTC_NOFEEDBACK "Désactiver le retour microphone lorsque la diffusion est active"
#define MSG_OPTC_NOAUXINFEEDBACK "Désactiver le retour de l'entrée auxiliaire lorsque la diffusion est active"
#define MSG_OPTC_ADJUSTMUSIC "Ajuster le volume de la musique en fonction du microphone"
#define MSG_OPTC_AUTOTITLE "Envoyer le titre de la chanson en cours de diffusion"
#define MSG_OPTC_USEJINGLES "Activer le mode jingle (avec la touche espace dans la playlist)"
#define MSG_OPT_ADVANCED L"Avanc\xE9"
#define MSG_OPTX_SCRIPTING "Activer le scripting lua"
#define MSG_OPTX_WEBSERV "Activer le serveur web de contrôle du lecteur"
#define MSG_OPTX_SERVPORT "Port d'écoute:"
#define MSG_OPT_GENERAL L"G\xE9n\xE9ral"
#define MSG_OPTG_CHECKUPDATES "Vérifier les mises à jour à chaque démarrage"
#define MSG_OPTG_RELOADLAST "Au démarrage, reprendre la lecture là où elle avait été arrêtée la dernière fois"
#define MSG_CAST_TITLE "Diffusion sur le web"
#define MSG_CAST_TYPE "Type : "
#define MSG_CAST_FORMAT "Format : "
#define MSG_CAST_HOST "Serveur : "
#define MSG_CAST_PORT "Port : "
#define MSG_CAST_STREAMID "Point de montage : "
#define MSG_CAST_NAME "Nom du serveur : "
#define MSG_CAST_PASSWORD "Mot de passe : "
#define MSG_CAST_URL "URL du site web : "
#define MSG_CAST_GENRE "Genre : "
#define MSG_CAST_DESC "Description : "
#define MSG_SHOUTCAST "Shoutcast"
#define MSG_SHOUTCAST2 "Shoutcast 2"
#define MSG_ICECAST "Icecast"
#define MSG_CASTDIRECT "Serveur direct"
#define MSG_CASTFAIL L"La diffusion sur le web n'a pas pu d\xE9marrer."
#define MSG_TEXTDLG "Paroles et sous-titres"
#define MSG_MIDIDLG "Panneau MIDI"
#define MSG_MIDI_LBLLYRIC "Paroles et sous-titres : "
#define MSG_MIDI_CHANNEL "Canal "
#define MSG_LEVELSDLG "Niveaux"
#define MSG_LEV_VOL "Volume musique : "
#define MSG_LEV_MIC "Retour microphone : "
#define MSG_LEV_AUXIN "Retour entr\xE9" "e auxiliaire : "
#define MSG_LEV_BVOL "Emission musique : "
#define MSG_LEV_BMIC "Emission micro : "
#define MSG_LEV_BAUXIN "Emission entr\xE9" "e auxiliaire : "
#define MSG_TBPOSITION "Position"
#define MSG_TBVOLUME "Volume"
#define MSG_ABOUTTITLE L"\xC0 propos de 6Player"
#define MSG_ABOUTTEXT "6Player, version 4.1 alpha\r\nCopyright \xA9 2011-2015, QuentinC\r\nPlus d'infos sur http://quentinc.net/ "

#define MSG_FILEMENU "&Fichier"
#define MSG_FILEOPEN "&Ouvrir...\aCtrl+O"
#define MSG_FILEOPENURL "Ouvrir une &URL...\aCtrl+U"
#define MSG_FILEOPENAPPEND "Ouvrir et &ajouter à la liste de lecture...\aCtrl+Maj+O"
#define MSG_FILEOPENURLAPPEND "Ou&vrir une URL et ajouter à la liste de lecture...\aCtrl+Maj+U"
#define MSG_FILEOPENDIR "Ouvrir un &dossier...\aCtrl+D"
#define MSG_FILEOPENDIRAPPEND "Ouvrir un dossier et a&jouter à la liste de lecture...\aCtrl+Maj+D"
#define MSG_FILEOPENRADIO "Radios...\aAlt+R"
#define MSG_FILESAVE "&Enregistrer sous...\aCtrl+S"
#define MSG_FILEINFO4 "Propriétés\aF3"
#define MSG_FILESAVEALL "E&xporter toute la playlist"
#define MSG_FILESAVEALL2 "Exporter toute la playlist"
#define MSG_FILEOPTIONS "Opt&ions...\aCtrl+P"
#define MSG_FILEQUIT "&Quitter\aAlt+F4"
#define MSG_LECTMENU "&Lecture"
#define MSG_LECTPAUSE "&Pause/reprise\aC"
#define MSG_LECTNEXT "Morceau &suivant\aL"
#define MSG_LECTPREV "Morceau pré&cédent\aK"
#define MSG_LECTGOTOTIME "A&tteindre...\aCtrl+J"
#define MSG_LECTSAVE "&Enregistrer la playlist...\aCtrl+Maj+S"
#define MSG_LECTDEV "P\xE9riph\xE9riques audio...\aF6"
#define MSG_LECTLOOP "Lecture en &boucle\aI"
#define MSG_LECTRAND "Lecture aléatoi&re\aP"
#define MSG_LECTREVERSE "Lecture in&versée\aMaj+P"
#define MSG_LECTINTRO "Mode &intro\aMaj+I"
#define MSG_LECTFADE "&Fondu enchaîné\aN"
#define MSG_PLISTMENU "Playlis&t"
#define MSG_PLMDELSONG "Su&pprimer le morceau en cours de la playlist\aSuppr"
#define MSG_PLMSHOWPLAYLIST "&Afficher la playlist\aAlt+P"
#define MSG_INDEXPLAYLIST "Inde&xer la playlist\aCtrl+Maj+X"
#define MSG_RECORD_TOGGLE "Activer le &microphone\aF4"
#define MSG_AUXRECORD_TOGGLE "Activer 'entrée auximilaire\aMaj+F4"
#define MSG_MIDIDLG_TOGGLE "Afficher le panneau M&IDI\aAlt+M"
#define MSG_TEXTDLG_TOGGLE "Afficher paroles et sous-titres\aAlt+X"
#define MSG_SHOWLEVELS "Afficher les niveaux\aAlt+V"
#define MSG_CASTING "Diffusion sur le &web...\aCtrl+Maj+W"
#define MSG_EFFECTSMENU "Effet&s"
#define MSG_EFF_MODE "Appliquer à"
#define MSG_EFF_MODE1 "Lecture"
#define MSG_EFF_MODE2 "Microphone"
#define MSG_EFF_MODE3 "Emission"
#define MSG_EFF_MODE4 "Entrée auxiliaire"
#define MSG_HELPMENU "&?"
#define MSG_HELPABOUT "&A propos de..."

#endif
